Author: Chufan Deng

Q1.
(SELECT USER_ID, NAME
FROM USERS
MINUS
SELECT p.USER_ID, u.NAME
FROM USERS u
INNER JOIN POSTS p ON u.USER_ID = p.USER_ID)
INTERSECT
SELECT c.COMMENTER _USER_ID, u.NAME
FROM USERS u
INNER JOIN COMMENTS c ON u.USER_ID = c.COMMENTER _USER_ID
WHERE c.POST_ID = 5;

Q2.
SELECT USER_ID
FROM USER
WHERE GENDER = 'F' AND USER_ID IN
(SELECT FRIEND_ID
FROM FRIENDSHIPS
WHERE USER_ID = 1
INTERSECT
SELECT FRIEND_ID
FROM FRIENDSHIPS
WHERE USER_ID = 2);

Q3.
SELECT USER_ID
FROM FRIENDSHIP
WHERE FRIEND_ID IN
(SELECT u.USER_ID
FROM USERS u
INNER JOIN POSTS p ON u.USER_ID = p.USER_ID)
GROUP BY USER_ID
HAVING COUNT(FRIEND_ID) > 2;

Q4.
SELECT DISTINCT USER_ID, COUNT(FRIEND_ID)
FROM FRIENDSHIP
WHERE USER_ID IN
(SELECT USER_ID
FROM USER
WHERE GENDER = 'F' AND DATE_OF_BIRTH > date '1990-12-20'
INTERSECT
SELECT c.COMMENTER _USER_ID
FROM USERS u
INNER JOIN COMMENTS c ON u.USER_ID = c.COMMENTER _USER_ID
WHERE c.POST_ID = 10)
GROUP BY USER_ID;

Q5.
SELECT FRIEND_ID
FROM FRIENDSHIP
WHERE USER_ID =
(SELECT USER_ID
FROM POSTS
WHERE POST_ID = 7)
INTERSECT
SELECT c.COMMENTER _USER_ID
FROM USERS u
INNER JOIN COMMENTS c ON u.USER_ID = c.COMMENTER _USER_ID
WHERE c.POST_ID = 7
